# Base configs
baseurl: "https://henryygu.github.io/BABINM/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-46465113-2"

# UI configs
title: "Born and Bread in New Malden"
subtitle: "Cakes for everyone"
author: "BABINM"
header:
 title: "Portfolio"
 subtitle: "by BABINM"
footer:
 name: "Welcome to BABINM"
 bio: "We love Cakes!"
 #github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
#web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/henryygu"
  twitter: "https://www.twitter.com/henryygu"
  instagram: "https://www.instagram.com/henryygu"
  dribbble: "https://dribbble.com/henryygu"
  linkedin: "https://in.linkedin.com/in/henryygu"
  github: "https://www.github.com/henryygu"
