# Base configs
baseurl: "https://henryygu.github.io/BABINM/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Born and Bread in New Malden"
subtitle: "Cakes for Any Occasion"
author: "Ram Patra"
header:
 title: "Born and Bread in New Malden"
 #subtitle: "by Ram Patra"
footer:
 name: "Hey there, we are Born and Bread in New Malden"
 bio: "We love making cakes"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ramswarooppatra"
  instagram: "https://www.instagram.com/ramswarooppatra"
  dribbble: "https://dribbble.com/ramswaroop"
  linkedin: "https://in.linkedin.com/in/ramswarooppatra"
  github: "https://www.github.com/ramswaroop"
